# -*- coding: utf-8 -*-
"""capstone 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_WuHGT74S9Hv3vpcoV_GcEMlVyM7aBuF
"""

pip install torch torchvision scikit-learn matplotlib numpy opencv-python grad-cam tqdm

import torch
from torchvision import datasets, transforms
from torch.utils.data import DataLoader, WeightedRandomSampler
import numpy as np
from google.colab import drive

drive.mount('/content/drive')

DATA_DIR = "/content/drive/MyDrive/capstone project 2"

transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.RandomHorizontalFlip(p=0.5),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])

dataset = datasets.ImageFolder(DATA_DIR, transform=transform)

# ---- Handle class imbalance (ETHICAL DETAIL MOST MISS) ----
targets = np.array(dataset.targets)
class_sample_count = np.bincount(targets)
weights = 1. / class_sample_count
samples_weight = weights[targets]

sampler = WeightedRandomSampler(
    samples_weight,
    num_samples=len(samples_weight),
    replacement=True
)

loader = DataLoader(
    dataset,
    batch_size=32,
    sampler=sampler,
    num_workers=2,
    pin_memory=True
)

print("Classes:", dataset.classes)

import torchvision.models as models
import torch.nn as nn
import torch # Import torch to use its device utilities

model = models.efficientnet_b0(weights="IMAGENET1K_V1")

model.classifier[1] = nn.Linear(
    model.classifier[1].in_features, 2
)

# Dynamically set the device to GPU if available, otherwise CPU
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = model.to(device)

print(f"Model moved to {device}")

from torch.optim import Adam
from torch.nn import CrossEntropyLoss
from tqdm import tqdm

optimizer = Adam(model.parameters(), lr=1e-4)
criterion = CrossEntropyLoss()

def train_epoch(model, loader):
    model.train()
    running_loss = 0

    for images, labels in tqdm(loader):
        images = images.cuda()
        labels = labels.cuda()

        optimizer.zero_grad()
        outputs = model(images)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        running_loss += loss.item()

    return running_loss / len(loader)

from sklearn.metrics import classification_report, confusion_matrix

def evaluate(model, loader):
    model.eval()
    y_true, y_pred = [], []

    with torch.no_grad():
        for images, labels in loader:
            images = images.cuda()
            outputs = model(images)
            preds = outputs.argmax(1).cpu().numpy()

            y_true.extend(labels.numpy())
            y_pred.extend(preds)

    print(confusion_matrix(y_true, y_pred))
    print(classification_report(
        y_true, y_pred,
        target_names=dataset.classes
    ))

from pytorch_grad_cam import GradCAM
from pytorch_grad_cam.utils.image import show_cam_on_image
import cv2

target_layer = model.features[-1]
cam = GradCAM(model=model, target_layers=[target_layer])

def explain(image_path):
    img = cv2.imread(image_path)
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    img_resized = cv2.resize(img, (224, 224)) / 255.0

    tensor = transform(img).unsqueeze(0).cuda()
    grayscale_cam = cam(tensor)[0]

    visualization = show_cam_on_image(img_resized, grayscale_cam)
    return visualization

"""Train - Validation split

"""

from sklearn.model_selection import train_test_split
from torch.utils.data import DataLoader, Subset
import numpy as np
from torchvision.datasets import ImageFolder
from torchvision import transforms # Import transforms here for transform definition

# Redefine transform to ensure it's available in this cell
transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.RandomHorizontalFlip(p=0.5),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])

dataset = ImageFolder(root=r"/content/drive/MyDrive/capstone project 2/AI-face-detection-Dataset", transform=transform)

indices = np.arange(len(dataset))
train_idx, val_idx = train_test_split(
    indices, test_size=0.2, stratify=dataset.targets, random_state=42
)

train_dataset = Subset(dataset, train_idx)
val_dataset = Subset(dataset, val_idx)

train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=32, shuffle=False)

from google.colab import drive
drive.mount('/content/drive')

import pickle
import torch

# Define a filename for the pickle file
model_filename = 'trained_model.pkl'

# --- Saving the model using pickle ---
# For PyTorch models, torch.save is generally preferred.
# However, if you want to pickle the entire model object (including its class definition if not in global scope),
# you can use pickle. This might not be ideal for complex PyTorch models
# if the class definition isn't available when loading in a different environment.

# It's better practice to save PyTorch models' state_dict for portability
# torch.save(model.state_dict(), 'model_state_dict.pth')
# But for demonstration of pickle, we'll save the whole model object.

print(f"Saving the model to {model_filename}...")
with open(model_filename, 'wb') as f:
    pickle.dump(model, f)
print("Model saved successfully!")

# --- Loading the model from the pickle file ---
print(f"\nLoading the model from {model_filename}...")
with open(model_filename, 'rb') as f:
    loaded_model = pickle.load(f)
print("Model loaded successfully!")

# You can verify it by printing the loaded model
# print(loaded_model)

# If you saved only the state_dict with torch.save, you would load it like this:
# loaded_state_dict = torch.load('model_state_dict.pth')
# new_model = YourModelClass(*args, **kwargs) # Recreate your model architecture
# new_model.load_state_dict(loaded_state_dict)
# new_model.eval()

"""Learning rate scheduler

"""

import torch.optim as optim
import torchvision.models as models
import torch.nn as nn
import torch # Import torch to use its device utilities

# Define the model (copied from cell Okg6gRoHhuQl)
model = models.efficientnet_b0(weights="IMAGENET1K_V1")
model.classifier[1] = nn.Linear(model.classifier[1].in_features, 2)

# Dynamically set the device (copied from cell Okg6gRoHhuQl)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = model.to(device)

optimizer = optim.Adam(model.parameters(), lr=1e-4)

scheduler = optim.lr_scheduler.ReduceLROnPlateau(
    optimizer,
    mode='min',
    factor=0.5,
    patience=3
)

"""proper training and validation loop"""

from torch.nn import CrossEntropyLoss # Import CrossEntropyLoss

num_epochs = 20

train_losses = []
val_losses = []

criterion = CrossEntropyLoss() # Define criterion here

for epoch in range(num_epochs):

    # --------------------
    # TRAINING LOOP
    # --------------------
    model.train()
    running_train_loss = 0.0

    for images, labels in train_loader:
        images = images.to(device)
        labels = labels.to(device)

        optimizer.zero_grad()

        outputs = model(images)
        loss = criterion(outputs, labels)

        loss.backward()
        optimizer.step()

        running_train_loss += loss.item()

    train_loss = running_train_loss / len(train_loader)
    train_losses.append(train_loss)


    # --------------------
    # VALIDATION LOOP
    # --------------------
    model.eval()
    running_val_loss = 0.0

    with torch.no_grad():
        for images, labels in val_loader:
            images = images.to(device)
            labels = labels.to(device)

            outputs = model(images)
            loss = criterion(outputs, labels)

            running_val_loss += loss.item()

    val_loss = running_val_loss / len(val_loader)
    val_losses.append(val_loss)

    # Scheduler step MUST be here
    scheduler.step(val_loss)

    print(f"Epoch [{epoch+1}/{num_epochs}] "
          f"Train Loss: {train_loss:.4f} "
          f"Val Loss: {val_loss:.4f}")
    early_stopping(val_loss)

    if early_stopping.early_stop:
        print("Early stopping triggered")
        break

class EarlyStopping:
    def __init__(self, patience=5, delta=0):
        self.patience = patience
        self.delta = delta
        self.best_loss = None
        self.counter = 0
        self.early_stop = False

    def __call__(self, val_loss):
        if self.best_loss is None:
            self.best_loss = val_loss
        elif val_loss > self.best_loss - self.delta:
            self.counter += 1
            if self.counter >= self.patience:
                self.early_stop = True
        else:
            self.best_loss = val_loss
            self.counter = 0

early_stopping = EarlyStopping(patience=5)

import matplotlib.pyplot as plt

# Dummy values added to get a curve based on the last training run's output.
# Please re-run the training loop (WIPunW2IK_8T) to get actual training data for the curve.
train_losses = [0.0004, 0.0004, 0.0003, 0.0005, 0.0004, 0.0003, 0.0088, 0.0003, 0.0005, 0.0004, 0.0011]
val_losses = [0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0000, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001]
train_accs, val_accs = [], []

plt.figure()
plt.plot(train_losses)
plt.plot(val_losses)
plt.title("Loss Curve")
plt.legend(["Train", "Validation"])
plt.show()

from sklearn.metrics import roc_curve, auc
import numpy as np

model.eval()
all_probs = []
all_labels = []

with torch.no_grad():
    for images, labels in val_loader:
        images = images.to(device)
        outputs = model(images)
        probs = torch.softmax(outputs, dim=1)[:,1]
        all_probs.extend(probs.cpu().numpy())
        all_labels.extend(labels.numpy())

fpr, tpr, _ = roc_curve(all_labels, all_probs)
roc_auc = auc(fpr, tpr)

plt.figure()
plt.plot(fpr, tpr)
plt.title(f"ROC Curve (AUC = {roc_auc:.4f})")
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.show()

from torchvision import models

# EfficientNet
eff_model = models.efficientnet_b0(pretrained=True)
eff_model.classifier[1] = nn.Linear(eff_model.classifier[1].in_features, 2)

# ResNet
res_model = models.resnet18(pretrained=True)
res_model.fc = nn.Linear(res_model.fc.in_features, 2)

torch.save(model.state_dict(), "best_model.pth")

model.load_state_dict(torch.load("best_model.pth"))
model.eval()



import gradio as gr
from PIL import Image
import cv2
import torch
import numpy as np

# Ensure the model is in evaluation mode
model.eval()

# Define class names for the binary classification
# (Assuming the model is intended for 'Real Face' vs 'AI-Generated Face')
class_names = ["Real Face", "AI-Generated Face"]

def predict_and_explain_app(input_image_pil: Image.Image):
    # Determine the device for inference
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model.to(device)

    # Preprocess the input PIL image using the existing transform
    input_tensor = transform(input_image_pil).unsqueeze(0).to(device) # Add batch dimension

    # Make prediction
    with torch.no_grad():
        outputs = model(input_tensor)
        probabilities = torch.softmax(outputs, dim=1)
        predicted_class_idx = torch.argmax(probabilities, dim=1).item()

    predicted_label = class_names[predicted_class_idx]
    confidence = probabilities[0, predicted_class_idx].item()

    # Prepare image for GradCAM visualization
    # Convert PIL image to numpy array (RGB, 0-255) for OpenCV and GradCAM utility
    input_image_np = np.array(input_image_pil)
    # Resize to 224x224 and normalize to 0-1 for show_cam_on_image
    img_resized_for_cam = cv2.resize(input_image_np, (224, 224)) / 255.0

    # Generate GradCAM explanation
    # Re-associate cam with the potentially moved loaded_model
    cam.model = model # This line ensures the cam object uses the correct model
    # The cam object was initialized in a previous cell using `target_layer` and `model`
    grayscale_cam = cam(input_tensor)[0]

    # Create visualization image (returns numpy array, RGB, 0-255)
    visualization = show_cam_on_image(img_resized_for_cam, grayscale_cam, use_rgb=True)

    # Return prediction text and GradCAM image
    return f"Prediction: {predicted_label} (Confidence: {confidence:.2f})", Image.fromarray(visualization)

# Create the Gradio interface
iface = gr.Interface(
    fn=predict_and_explain_app,
    inputs=gr.Image(type="pil", label="Upload Image"),
    outputs=[
        gr.Textbox(label="Prediction"),
        gr.Image(type="pil", label="GradCAM Visualization")
    ],
    title="AI Face Detection with GradCAM Explanation",
    description="Upload an image to detect if it's a real or AI-generated face and see a GradCAM visualization of the model's focus."
)

# Launch the app (this line is typically included for local testing or for Hugging Face Spaces)
iface.launch()

"""## Launch Gradio app

### Subtask:
Launch the Gradio application to perform AI face detection with GradCAM explanations.

## Summary:

### Q&A
The Gradio application for AI face detection using the model saved in "best_model.pth" with GradCAM explanations has been successfully set up and launched.

### Data Analysis Key Findings
*   The Gradio application code was successfully modified to use the `model` variable, ensuring predictions are made using the pre-trained model loaded from `best_model.pth`.
*   The `cam` object, responsible for GradCAM explanations, was correctly updated to associate with the `model`, allowing for accurate visualization of the model's focus.
*   The Gradio application launched successfully, generating a public URL for access, indicating it is ready for user interaction.

### Insights or Next Steps
*   The Gradio application is now fully functional and accessible via the generated public URL, allowing users to upload images and receive AI face detection predictions along with GradCAM explanations.
*   The next step should involve testing the launched Gradio application with a diverse set of real and AI-generated face images to evaluate its performance and the clarity of the GradCAM explanations.
"""